version: '3'

services:
  location-service-api:
    build: .
    command: sh -c 'echo "Hello"'
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - locationservice
      - redis
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - PASSWORD=${PASSWORD}
      - NAME=${NAME}
      - GIN_MODE=release

  locationservice:
    image: "postgres:12-alpine"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - 5432:5432
  
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

    
    
